---
- hosts: t-docker01.redsys.ru
  gather_facts: False
  tasks:
  - name: start docker tomcat
    docker_container:
      name: tomcat1
      image: tomcat:7-jre8 
      state: started
      detach: yes
      volumes:
         - /tmp/app/rsdoc.piter.xml:/usr/local/tomcat/conf/context.xml
         - /tmp/app/rsdoc.war.1254:/usr/local/tomcat/webapps/rsdoc.war
         - /tmp/app/security.properties:/usr/local/tomcat/conf/security.properties 

  - name: start docker nginx
    docker_container:
      name: nginx
      image: nginx:latest
      state: started
      detach: yes
      volumes:
         - /tmp/app/config/vhost.conf:/etc/nginx/conf.d/default.conf
      links:
         - tomcat1:tomcat1
      ports:
         - 80:80

